# Generated by Django 4.1.3 on 2025-09-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kapal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kapal', models.CharField(max_length=200, verbose_name='Nama Kapal')),
                ('nomor_registrasi', models.CharField(max_length=100, unique=True, verbose_name='Nomor Registrasi')),
                ('jenis_kapal', models.CharField(max_length=100, verbose_name='Jenis Kapal')),
                ('ukuran_kapal', models.CharField(max_length=50, verbose_name='Ukuran Kapal')),
                ('tahun_pembuatan', models.IntegerField(verbose_name='Tahun Pembuatan')),
                ('pemilik', models.CharField(max_length=200, verbose_name='Pemilik')),
                ('pelabuhan_asal', models.CharField(max_length=200, verbose_name='Pelabuhan Asal')),
                ('dokumen', models.JSONField(blank=True, default=list, verbose_name='Dokumen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kapal',
                'verbose_name_plural': 'Kapal',
                'ordering': ['-created_at'],
            },
        ),
    ]
