# Generated by Django 4.1.3 on 2025-09-26 03:51

import django.core.validators
from django.db import migrations, models
import kapal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kapal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kapal', models.CharField(max_length=200, verbose_name='Nama Kapal')),
                ('nomor_registrasi', models.CharField(max_length=100, unique=True, verbose_name='Nomor Registrasi')),
                ('pemilik', models.CharField(max_length=200, verbose_name='Pemilik')),
                ('jenis_kapal', models.CharField(max_length=100, verbose_name='Jenis Kapal')),
                ('tonase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tonase (GT)')),
                ('panjang', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Panjang (m)')),
                ('lebar', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Lebar (m)')),
                ('tahun_pembuatan', models.IntegerField(verbose_name='Tahun Pembuatan')),
                ('pelabuhan_asal', models.CharField(max_length=200, verbose_name='Pelabuhan Asal')),
                ('dokumen', models.FileField(blank=True, help_text='Upload dokumen kapal (PDF, JPG, PNG). Maksimal 5 MB.', null=True, upload_to=kapal.models.kapal_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Dokumen Kapal')),
                ('status_dokumen', models.CharField(choices=[('lengkap', 'Lengkap'), ('tidak_lengkap', 'Tidak Lengkap'), ('dalam_proses', 'Dalam Proses')], default='tidak_lengkap', max_length=20, verbose_name='Status Dokumen')),
                ('tanggal_upload_dokumen', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Upload Dokumen')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kapal',
                'verbose_name_plural': 'Kapal',
                'ordering': ['-created_at'],
            },
        ),
    ]
